package test

import (
	"context"
	"database/sql"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/pthm/melange/pkg/migrator"
	"github.com/pthm/melange/test/testutil"
)

const signatureSchema = `
model
  schema 1.1

type user

type folder
  relations
    define viewer: [user]

type document
  relations
    define folder: [folder]
    define viewer: [user, folder#viewer]
`

// createTuplesTable gives the generated functions something to read. The
// signature tests only care that calls resolve, not what they return.
func createTuplesTable(t *testing.T, ctx context.Context, db *sql.DB) {
	t.Helper()
	_, err := db.ExecContext(ctx, `
		CREATE TABLE IF NOT EXISTS melange_tuples (
			subject_type TEXT, subject_id TEXT, relation TEXT,
			object_type TEXT, object_id TEXT
		)`)
	require.NoError(t, err)
}

// functionSignatures returns every signature PostgreSQL holds for a function
// name, e.g. "list_accessible_objects(text,text,text,text,integer,text)".
func functionSignatures(t *testing.T, ctx context.Context, db *sql.DB, name string) []string {
	t.Helper()
	rows, err := db.QueryContext(ctx, `
		SELECT p.oid::regprocedure::text
		FROM pg_proc p
		JOIN pg_namespace n ON n.oid = p.pronamespace
		WHERE n.nspname = 'public' AND p.proname = $1
		ORDER BY 1`, name)
	require.NoError(t, err)
	defer func() { _ = rows.Close() }()

	var sigs []string
	for rows.Next() {
		var sig string
		require.NoError(t, rows.Scan(&sig))
		sigs = append(sigs, sig)
	}
	require.NoError(t, rows.Err())
	return sigs
}

// TestMigration_DropsStaleArityOverload covers the upgrade path where a
// generated function's argument list changed between releases.
//
// PostgreSQL identifies a function by (name, argument types), so CREATE OR
// REPLACE with a new argument list adds an overload rather than replacing the
// old one. Both then match any call that fits both arities, and PostgreSQL
// refuses it as ambiguous — which takes out not just the changed call but every
// call the generated functions make to each other.
//
// Tracking functions by bare name cannot see this, so the migrator compares
// signatures: applying the schema creates exactly one signature per expected
// name, and any additional signature that predates the apply is stale.
func TestMigration_DropsStaleArityOverload(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping integration test in short mode")
	}

	db := testutil.EmptyDB(t)
	ctx := context.Background()
	m := migrator.NewMigrator(db, "")
	createTuplesTable(t, ctx, db)

	// Stand in for a function generated by an older release, before p_filter
	// widened the signature. Body is irrelevant; only the signature matters.
	_, err := db.ExecContext(ctx, `
		CREATE FUNCTION list_accessible_objects(
			p_subject_type TEXT, p_subject_id TEXT, p_relation TEXT,
			p_object_type TEXT, p_limit INT DEFAULT NULL, p_after TEXT DEFAULT NULL
		) RETURNS TABLE(object_id TEXT, next_cursor TEXT) AS $$
			SELECT NULL::TEXT, NULL::TEXT WHERE FALSE;
		$$ LANGUAGE sql STABLE`)
	require.NoError(t, err, "seeding the legacy signature")

	require.Len(t, functionSignatures(t, ctx, db, "list_accessible_objects"), 1,
		"precondition: exactly the legacy signature is deployed")

	migrateSchema(t, ctx, m, signatureSchema, migrator.InternalMigrateOptions{Version: "v0.9.4"})

	sigs := functionSignatures(t, ctx, db, "list_accessible_objects")
	assert.Len(t, sigs, 1, "the stale overload should have been dropped, got %v", sigs)
	assert.Contains(t, sigs[0], "text,text,text,text,integer,text,text",
		"the surviving signature should be the one this release generates")

	// The point of dropping it: calls that fit both arities resolve again.
	// Before the fix these failed with 42725 "function ... is not unique".
	for _, call := range []string{
		`SELECT count(*) FROM list_accessible_objects('user','1','viewer','document')`,
		`SELECT count(*) FROM list_accessible_objects('user','1','viewer','document',NULL,NULL)`,
		`SELECT count(*) FROM list_accessible_objects('user','1','viewer','document',NULL,NULL,'folder@folder:1')`,
	} {
		var n int
		assert.NoError(t, db.QueryRowContext(ctx, call).Scan(&n), "call should resolve: %s", call)
	}
}

// TestMigration_KeepsSoleSignature guards the other direction: a normal
// re-apply must not mistake a function it just replaced for a stale overload.
func TestMigration_KeepsSoleSignature(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping integration test in short mode")
	}

	db := testutil.EmptyDB(t)
	ctx := context.Background()
	m := migrator.NewMigrator(db, "")
	createTuplesTable(t, ctx, db)

	migrateSchema(t, ctx, m, signatureSchema, migrator.InternalMigrateOptions{Version: "v0.9.4"})
	before := functionSignatures(t, ctx, db, "list_accessible_objects")
	require.Len(t, before, 1)

	// Force a second apply over the identical schema.
	migrateSchema(t, ctx, m, signatureSchema, migrator.InternalMigrateOptions{
		Version: "v0.9.4",
		Force:   true,
	})

	assert.Equal(t, before, functionSignatures(t, ctx, db, "list_accessible_objects"),
		"re-applying an unchanged schema should leave the signature untouched")

	var n int
	assert.NoError(t, db.QueryRowContext(ctx,
		`SELECT count(*) FROM list_accessible_objects('user','1','viewer','document')`).Scan(&n))
}
