# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: melange

before:
  hooks:
    - ./scripts/verify-release.sh
    - go mod tidy

builds:
  # Non-darwin builds (no signing needed)
  - id: melange-linux-windows
    main: ./cmd/melange
    binary: melange
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/pthm/melange/internal/version.Version={{.Version}}
      - -X github.com/pthm/melange/internal/version.Commit={{.Commit}}
      - -X github.com/pthm/melange/internal/version.Date={{.Date}}

  # Darwin builds with code signing
  - id: melange-darwin
    main: ./cmd/melange
    binary: melange
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/pthm/melange/internal/version.Version={{.Version}}
      - -X github.com/pthm/melange/internal/version.Commit={{.Commit}}
      - -X github.com/pthm/melange/internal/version.Date={{.Date}}
    hooks:
      post:
        - cmd: ./scripts/sign-macos.sh "{{ .Path }}" --notarize
          output: true

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - LICENSE
      - README.md
      - THIRD_PARTY_NOTICES

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

release:
  github:
    owner: pthm
    name: melange
  draft: false
  prerelease: auto
  mode: replace
  name_template: "{{.ProjectName}} v{{.Version}}"

changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

homebrew_casks:
  - name: melange
    repository:
      owner: pthm
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Casks
    homepage: "https://github.com/pthm/melange"
    description: "PostgreSQL Fine-Grained Authorization - OpenFGA to SQL compiler"
    license: "MIT"

publishers:
  - name: npm
    ids:
      - default
    cmd: sh -c 'cd clients/typescript && pnpm build && pnpm publish --access public --no-git-checks'
    stdin: '{{ .IsSnapshot | not }}'
