// Code generated by melange. DO NOT EDIT.

package authz

import (
	"fmt"

	"github.com/pthm/melange"
)

// ObjectType constants from schema.
const (
	TypeIssue melange.ObjectType = "issue"
	TypeOrganization melange.ObjectType = "organization"
	TypePullRequest melange.ObjectType = "pull_request"
	TypeRepository melange.ObjectType = "repository"
	TypeTeam melange.ObjectType = "team"
	TypeUser melange.ObjectType = "user"
)

// Relations from schema.
// ALL relations are generated, not just "can_*" permissions.
const (
	RelAdmin melange.Relation = "admin"
	RelAssignee melange.Relation = "assignee"
	RelAuthor melange.Relation = "author"
	RelBillingManager melange.Relation = "billing_manager"
	RelCanAdmin melange.Relation = "can_admin"
	RelCanClose melange.Relation = "can_close"
	RelCanDelete melange.Relation = "can_delete"
	RelCanEdit melange.Relation = "can_edit"
	RelCanMerge melange.Relation = "can_merge"
	RelCanRead melange.Relation = "can_read"
	RelCanReview melange.Relation = "can_review"
	RelCanWrite melange.Relation = "can_write"
	RelMaintainer melange.Relation = "maintainer"
	RelMember melange.Relation = "member"
	RelOrg melange.Relation = "org"
	RelOwner melange.Relation = "owner"
	RelReader melange.Relation = "reader"
	RelRepo melange.Relation = "repo"
	RelReviewer melange.Relation = "reviewer"
	RelWriter melange.Relation = "writer"
)

// Object constructors.

// Issue creates a issue object for relation checks.
func Issue(id int64) melange.Object { return melange.Object{Type: TypeIssue, ID: fmt.Sprint(id)} }

// Organization creates a organization object for relation checks.
func Organization(id int64) melange.Object { return melange.Object{Type: TypeOrganization, ID: fmt.Sprint(id)} }

// PullRequest creates a pull_request object for relation checks.
func PullRequest(id int64) melange.Object { return melange.Object{Type: TypePullRequest, ID: fmt.Sprint(id)} }

// Repository creates a repository object for relation checks.
func Repository(id int64) melange.Object { return melange.Object{Type: TypeRepository, ID: fmt.Sprint(id)} }

// Team creates a team object for relation checks.
func Team(id int64) melange.Object { return melange.Object{Type: TypeTeam, ID: fmt.Sprint(id)} }

// User creates a user object for relation checks.
func User(id int64) melange.Object { return melange.Object{Type: TypeUser, ID: fmt.Sprint(id)} }

// Wildcard constructors for public access patterns.

// AnyIssue returns a wildcard issue that matches type:* tuples.
func AnyIssue() melange.Object { return melange.Object{Type: TypeIssue, ID: "*"} }

// AnyOrganization returns a wildcard organization that matches type:* tuples.
func AnyOrganization() melange.Object { return melange.Object{Type: TypeOrganization, ID: "*"} }

// AnyPullRequest returns a wildcard pull_request that matches type:* tuples.
func AnyPullRequest() melange.Object { return melange.Object{Type: TypePullRequest, ID: "*"} }

// AnyRepository returns a wildcard repository that matches type:* tuples.
func AnyRepository() melange.Object { return melange.Object{Type: TypeRepository, ID: "*"} }

// AnyTeam returns a wildcard team that matches type:* tuples.
func AnyTeam() melange.Object { return melange.Object{Type: TypeTeam, ID: "*"} }

// AnyUser returns a wildcard user that matches type:* tuples.
func AnyUser() melange.Object { return melange.Object{Type: TypeUser, ID: "*"} }

